version: "3.2"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
     - "6379:6379"

  mongo:
    image: 'mongo:4.2.6-bionic'
    container_name: mongo
    ports:
        - '27017:27017'
    volumes:
        - ./mongodata:/data/db
    restart: always
  # Mongo Express Web-based MongoDB admin interface
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - 'mongo'
    ports:
      - '8081:8081'
    restart: always
